images:
    allowed_values:
    - .jpg
    - .png
    - .jpeg
spreadsheets:
    allowed_values:
    - .csv
    - .numbers
    - .xlsx
tableau:
    allowed_values:
    - .twb
yml:
    allowed_values:
    - .yml
